//export const fnOne = () => console.log('fnOne called');

export const japaneseCharacters = {
	hiragana: [
		{character: "あ", romaji: "a", type: "gojuon"},
		{character: "い", romaji: "i", type: "gojuon"},
		{character: "う", romaji: "u", type: "gojuon"},
		{character: "え", romaji: "e", type: "gojuon"},
		{character: "お", romaji: "o", type: "gojuon"},
		{character: "か", romaji: "ka", type: "gojuon"},
		{character: "き", romaji: "ki", type: "gojuon"},
		{character: "く", romaji: "ku", type: "gojuon"},
		{character: "け", romaji: "ke", type: "gojuon"},
		{character: "こ", romaji: "ko", type: "gojuon"},
		{character: "さ", romaji: "sa", type: "gojuon"},
		{character: "し", romaji: "shi", type: "gojuon"},
		{character: "す", romaji: "su", type: "gojuon"},
		{character: "せ", romaji: "se", type: "gojuon"},
		{character: "そ", romaji: "so", type: "gojuon"},
		{character: "た", romaji: "ta", type: "gojuon"},
		{character: "ち", romaji: "chi", type: "gojuon"},
		{character: "つ", romaji: "tsu", type: "gojuon"},
		{character: "て", romaji: "te", type: "gojuon"},
		{character: "と", romaji: "to", type: "gojuon"},
		{character: "な", romaji: "na", type: "gojuon"},
		{character: "に", romaji: "ni", type: "gojuon"},
		{character: "ぬ", romaji: "nu", type: "gojuon"},
		{character: "ね", romaji: "ne", type: "gojuon"},
		{character: "の", romaji: "no", type: "gojuon"},
		{character: "は", romaji: "ha", type: "gojuon"},
		{character: "ひ", romaji: "hi", type: "gojuon"},
		{character: "ふ", romaji: "fu", type: "gojuon"},
		{character: "へ", romaji: "he", type: "gojuon"},
		{character: "ほ", romaji: "ho", type: "gojuon"},
		{character: "ま", romaji: "ma", type: "gojuon"},
		{character: "み", romaji: "mi", type: "gojuon"},
		{character: "む", romaji: "mu", type: "gojuon"},
		{character: "め", romaji: "me", type: "gojuon"},
		{character: "も", romaji: "mo", type: "gojuon"},
		{character: "や", romaji: "ya", type: "yoon"},
		{character: "ゆ", romaji: "yu", type: "yoon"},
		{character: "よ", romaji: "yo", type: "yoon"},
		{character: "ら", romaji: "ra", type: "gojuon"},
		{character: "り", romaji: "ri", type: "gojuon"},
		{character: "る", romaji: "ru", type: "gojuon"},
		{character: "れ", romaji: "re", type: "gojuon"},
		{character: "ろ", romaji: "ro", type: "gojuon"},
		{character: "わ", romaji: "wa", type: "gojuon"},
		{character: "を", romaji: "wo", type: "gojuon"},
		{character: "ん", romaji: "n", type: "gojuon"},
	],
	hiragana_special: [
		{character: "が", romaji: "ga", type: "dakuten"},
		{character: "ぎ", romaji: "gi", type: "dakuten"},
		{character: "ぐ", romaji: "gu", type: "dakuten"},
		{character: "げ", romaji: "ge", type: "dakuten"},
		{character: "ご", romaji: "go", type: "dakuten"},
		{character: "ざ", romaji: "za", type: "dakuten"},
		{character: "じ", romaji: "ji", type: "dakuten"},
		{character: "ず", romaji: "zu", type: "dakuten"},
		{character: "ぜ", romaji: "ze", type: "dakuten"},
		{character: "ぞ", romaji: "zo", type: "dakuten"},
		{character: "だ", romaji: "da", type: "dakuten"},
		{character: "ぢ", romaji: "ji", type: "dakuten"},
		{character: "づ", romaji: "zu", type: "dakuten"},
		{character: "で", romaji: "de", type: "dakuten"},
		{character: "ど", romaji: "do", type: "dakuten"},
		{character: "ば", romaji: "ba", type: "dakuten"},
		{character: "び", romaji: "bi", type: "dakuten"},
		{character: "ぶ", romaji: "bu", type: "dakuten"},
		{character: "べ", romaji: "be", type: "dakuten"},
		{character: "ぼ", romaji: "bo", type: "dakuten"},
		{character: "ぱ", romaji: "pa", type: "handakuten"},
		{character: "ぴ", romaji: "pi", type: "handakuten"},
		{character: "ぷ", romaji: "pu", type: "handakuten"},
		{character: "ぺ", romaji: "pe", type: "handakuten"},
		{character: "ぽ", romaji: "po", type: "handakuten"},
	],
	hiragana_combinations: [
		{character: "きゃ", romaji: "kya", type: "yoon"},
		{character: "きゅ", romaji: "kyu", type: "yoon"},
		{character: "きょ", romaji: "kyo", type: "yoon"},
		{character: "ぎゃ", romaji: "gya", type: "yoon_dakuten"},
		{character: "ぎゅ", romaji: "gyu", type: "yoon_dakuten"},
		{character: "ぎょ", romaji: "gyo", type: "yoon_dakuten"},
		{character: "しゃ", romaji: "sha", type: "yoon"},
		{character: "しゅ", romaji: "shu", type: "yoon"},
		{character: "しょ", romaji: "sho", type: "yoon"},
		{character: "じゃ", romaji: "ja", type: "yoon_dakuten"},
		{character: "じゅ", romaji: "ju", type: "yoon_dakuten"},
		{character: "じょ", romaji: "jo", type: "yoon_dakuten"},
		{character: "ちゃ", romaji: "cha", type: "yoon"},
		{character: "ちゅ", romaji: "chu", type: "yoon"},
		{character: "ちょ", romaji: "cho", type: "yoon"},
		{character: "にゃ", romaji: "nya", type: "yoon"},
		{character: "にゅ", romaji: "nyu", type: "yoon"},
		{character: "にょ", romaji: "nyo", type: "yoon"},
		{character: "ひゃ", romaji: "hya", type: "yoon"},
		{character: "ひゅ", romaji: "hyu", type: "yoon"},
		{character: "ひょ", romaji: "hyo", type: "yoon"},
		{character: "びゃ", romaji: "bya", type: "yoon_dakuten"},
		{character: "びゅ", romaji: "byu", type: "yoon_dakuten"},
		{character: "びょ", romaji: "byo", type: "yoon_dakuten"},
		{character: "ぴゃ", romaji: "pya", type: "yoon_handakuten"},
		{character: "ぴゅ", romaji: "pyu", type: "yoon_handakuten"},
		{character: "ぴょ", romaji: "pyo", type: "yoon_handakuten"},
		{character: "みゃ", romaji: "mya", type: "yoon"},
		{character: "みゅ", romaji: "myu", type: "yoon"},
		{character: "みょ", romaji: "myo", type: "yoon"},
		{character: "りゃ", romaji: "rya", type: "yoon"},
		{character: "りゅ", romaji: "ryu", type: "yoon"},
		{character: "りょ", romaji: "ryo", type: "yoon"},
	],
	katakana: [
		{character: "ア", romaji: "a", type: "gojuon"},
		{character: "イ", romaji: "i", type: "gojuon"},
		{character: "ウ", romaji: "u", type: "gojuon"},
		{character: "エ", romaji: "e", type: "gojuon"},
		{character: "オ", romaji: "o", type: "gojuon"},
		{character: "カ", romaji: "ka", type: "gojuon"},
		{character: "キ", romaji: "ki", type: "gojuon"},
		{character: "ク", romaji: "ku", type: "gojuon"},
		{character: "ケ", romaji: "ke", type: "gojuon"},
		{character: "コ", romaji: "ko", type: "gojuon"},
		{character: "サ", romaji: "sa", type: "gojuon"},
		{character: "シ", romaji: "shi", type: "gojuon"},
		{character: "ス", romaji: "su", type: "gojuon"},
		{character: "セ", romaji: "se", type: "gojuon"},
		{character: "ソ", romaji: "so", type: "gojuon"},
		{character: "タ", romaji: "ta", type: "gojuon"},
		{character: "チ", romaji: "chi", type: "gojuon"},
		{character: "ツ", romaji: "tsu", type: "gojuon"},
		{character: "テ", romaji: "te", type: "gojuon"},
		{character: "ト", romaji: "to", type: "gojuon"},
		{character: "ナ", romaji: "na", type: "gojuon"},
		{character: "ニ", romaji: "ni", type: "gojuon"},
		{character: "ヌ", romaji: "nu", type: "gojuon"},
		{character: "ネ", romaji: "ne", type: "gojuon"},
		{character: "ノ", romaji: "no", type: "gojuon"},
		{character: "ハ", romaji: "ha", type: "gojuon"},
		{character: "ヒ", romaji: "hi", type: "gojuon"},
		{character: "フ", romaji: "fu", type: "gojuon"},
		{character: "ヘ", romaji: "he", type: "gojuon"},
		{character: "ホ", romaji: "ho", type: "gojuon"},
		{character: "マ", romaji: "ma", type: "gojuon"},
		{character: "ミ", romaji: "mi", type: "gojuon"},
		{character: "ム", romaji: "mu", type: "gojuon"},
		{character: "メ", romaji: "me", type: "gojuon"},
		{character: "モ", romaji: "mo", type: "gojuon"},
		{character: "ヤ", romaji: "ya", type: "yoon"},
		{character: "ユ", romaji: "yu", type: "yoon"},
		{character: "ヨ", romaji: "yo", type: "yoon"},
		{character: "ラ", romaji: "ra", type: "gojuon"},
		{character: "リ", romaji: "ri", type: "gojuon"},
		{character: "ル", romaji: "ru", type: "gojuon"},
		{character: "レ", romaji: "re", type: "gojuon"},
		{character: "ロ", romaji: "ro", type: "gojuon"},
		{character: "ワ", romaji: "wa", type: "gojuon"},
		{character: "ヲ", romaji: "wo", type: "gojuon"},
		{character: "ン", romaji: "n", type: "gojuon"},
	],
	hiragana_special: [
		{character: "が", romaji: "ga", type: "dakuten"},
		{character: "ぎ", romaji: "gi", type: "dakuten"},
		{character: "ぐ", romaji: "gu", type: "dakuten"},
		{character: "げ", romaji: "ge", type: "dakuten"},
		{character: "ご", romaji: "go", type: "dakuten"},
		{character: "ざ", romaji: "za", type: "dakuten"},
		{character: "じ", romaji: "ji", type: "dakuten"},
		{character: "ず", romaji: "zu", type: "dakuten"},
		{character: "ぜ", romaji: "ze", type: "dakuten"},
		{character: "ぞ", romaji: "zo", type: "dakuten"},
		{character: "だ", romaji: "da", type: "dakuten"},
		{character: "ぢ", romaji: "ji", type: "dakuten"},
		{character: "づ", romaji: "zu", type: "dakuten"},
		{character: "で", romaji: "de", type: "dakuten"},
		{character: "ど", romaji: "do", type: "dakuten"},
		{character: "ば", romaji: "ba", type: "dakuten"},
		{character: "び", romaji: "bi", type: "dakuten"},
		{character: "ぶ", romaji: "bu", type: "dakuten"},
		{character: "べ", romaji: "be", type: "dakuten"},
		{character: "ぼ", romaji: "bo", type: "dakuten"},
		{character: "ぱ", romaji: "pa", type: "handakuten"},
		{character: "ぴ", romaji: "pi", type: "handakuten"},
		{character: "ぷ", romaji: "pu", type: "handakuten"},
		{character: "ぺ", romaji: "pe", type: "handakuten"},
		{character: "ぽ", romaji: "po", type: "handakuten"},
	],
	hiragana_combinations: [
		{character: "きゃ", romaji: "kya", type: "yoon"},
		{character: "きゅ", romaji: "kyu", type: "yoon"},
		{character: "きょ", romaji: "kyo", type: "yoon"},
		{character: "ぎゃ", romaji: "gya", type: "yoon_dakuten"},
		{character: "ぎゅ", romaji: "gyu", type: "yoon_dakuten"},
		{character: "ぎょ", romaji: "gyo", type: "yoon_dakuten"},
		{character: "しゃ", romaji: "sha", type: "yoon"},
		{character: "しゅ", romaji: "shu", type: "yoon"},
		{character: "しょ", romaji: "sho", type: "yoon"},
		{character: "じゃ", romaji: "ja", type: "yoon_dakuten"},
		{character: "じゅ", romaji: "ju", type: "yoon_dakuten"},
		{character: "じょ", romaji: "jo", type: "yoon_dakuten"},
		{character: "ちゃ", romaji: "cha", type: "yoon"},
		{character: "ちゅ", romaji: "chu", type: "yoon"},
		{character: "ちょ", romaji: "cho", type: "yoon"},
		{character: "にゃ", romaji: "nya", type: "yoon"},
		{character: "にゅ", romaji: "nyu", type: "yoon"},
		{character: "にょ", romaji: "nyo", type: "yoon"},
		{character: "ひゃ", romaji: "hya", type: "yoon"},
		{character: "ひゅ", romaji: "hyu", type: "yoon"},
		{character: "ひょ", romaji: "hyo", type: "yoon"},
		{character: "びゃ", romaji: "bya", type: "yoon_dakuten"},
		{character: "びゅ", romaji: "byu", type: "yoon_dakuten"},
		{character: "びょ", romaji: "byo", type: "yoon_dakuten"},
		{character: "ぴゃ", romaji: "pya", type: "yoon_handakuten"},
		{character: "ぴゅ", romaji: "pyu", type: "yoon_handakuten"},
		{character: "ぴょ", romaji: "pyo", type: "yoon_handakuten"},
		{character: "みゃ", romaji: "mya", type: "yoon"},
		{character: "みゅ", romaji: "myu", type: "yoon"},
		{character: "みょ", romaji: "myo", type: "yoon"},
		{character: "りゃ", romaji: "rya", type: "yoon"},
		{character: "りゅ", romaji: "ryu", type: "yoon"},
		{character: "りょ", romaji: "ryo", type: "yoon"},
	],
	katakana: [
		{character: "ア", romaji: "a", type: "gojuon"},
		{character: "イ", romaji: "i", type: "gojuon"},
		{character: "ウ", romaji: "u", type: "gojuon"},
		{character: "エ", romaji: "e", type: "gojuon"},
		{character: "オ", romaji: "o", type: "gojuon"},
		{character: "カ", romaji: "ka", type: "gojuon"},
		{character: "キ", romaji: "ki", type: "gojuon"},
		{character: "ク", romaji: "ku", type: "gojuon"},
		{character: "ケ", romaji: "ke", type: "gojuon"},
		{character: "コ", romaji: "ko", type: "gojuon"},
		{character: "サ", romaji: "sa", type: "gojuon"},
		{character: "シ", romaji: "shi", type: "gojuon"},
		{character: "ス", romaji: "su", type: "gojuon"},
		{character: "セ", romaji: "se", type: "gojuon"},
		{character: "ソ", romaji: "so", type: "gojuon"},
		{character: "タ", romaji: "ta", type: "gojuon"},
		{character: "チ", romaji: "chi", type: "gojuon"},
		{character: "ツ", romaji: "tsu", type: "gojuon"},
		{character: "テ", romaji: "te", type: "gojuon"},
		{character: "ト", romaji: "to", type: "gojuon"},
		{character: "ナ", romaji: "na", type: "gojuon"},
		{character: "ニ", romaji: "ni", type: "gojuon"},
		{character: "ヌ", romaji: "nu", type: "gojuon"},
		{character: "ネ", romaji: "ne", type: "gojuon"},
		{character: "ノ", romaji: "no", type: "gojuon"},
		{character: "ハ", romaji: "ha", type: "gojuon"},
		{character: "ヒ", romaji: "hi", type: "gojuon"},
		{character: "フ", romaji: "fu", type: "gojuon"},
		{character: "ヘ", romaji: "he", type: "gojuon"},
		{character: "ホ", romaji: "ho", type: "gojuon"},
		{character: "マ", romaji: "ma", type: "gojuon"},
		{character: "ミ", romaji: "mi", type: "gojuon"},
		{character: "ム", romaji: "mu", type: "gojuon"},
		{character: "メ", romaji: "me", type: "gojuon"},
		{character: "モ", romaji: "mo", type: "gojuon"},
		{character: "ヤ", romaji: "ya", type: "yoon"},
		{character: "ユ", romaji: "yu", type: "yoon"},
		{character: "ヨ", romaji: "yo", type: "yoon"},
		{character: "ラ", romaji: "ra", type: "gojuon"},
		{character: "リ", romaji: "ri", type: "gojuon"},
		{character: "ル", romaji: "ru", type: "gojuon"},
		{character: "レ", romaji: "re", type: "gojuon"},
		{character: "ロ", romaji: "ro", type: "gojuon"},
		{character: "ワ", romaji: "wa", type: "gojuon"},
		{character: "ヲ", romaji: "wo", type: "gojuon"},
		{character: "ン", romaji: "n", type: "gojuon"},
	],
	katakana_special: [
		{character: "ガ", romaji: "ga", type: "dakuten"},
		{character: "ギ", romaji: "gi", type: "dakuten"},
		{character: "グ", romaji: "gu", type: "dakuten"},
		{character: "ゲ", romaji: "ge", type: "dakuten"},
		{character: "ゴ", romaji: "go", type: "dakuten"},
		{character: "ザ", romaji: "za", type: "dakuten"},
		{character: "ジ", romaji: "ji", type: "dakuten"},
		{character: "ズ", romaji: "zu", type: "dakuten"},
		{character: "ゼ", romaji: "ze", type: "dakuten"},
		{character: "ゾ", romaji: "zo", type: "dakuten"},
		{character: "ダ", romaji: "da", type: "dakuten"},
		{character: "ヂ", romaji: "ji", type: "dakuten"},
		{character: "ヅ", romaji: "zu", type: "dakuten"},
		{character: "デ", romaji: "de", type: "dakuten"},
		{character: "ド", romaji: "do", type: "dakuten"},
		{character: "バ", romaji: "ba", type: "dakuten"},
		{character: "ビ", romaji: "bi", type: "dakuten"},
		{character: "ブ", romaji: "bu", type: "dakuten"},
		{character: "ベ", romaji: "be", type: "dakuten"},
		{character: "ボ", romaji: "bo", type: "dakuten"},
		{character: "パ", romaji: "pa", type: "handakuten"},
		{character: "ピ", romaji: "pi", type: "handakuten"},
		{character: "プ", romaji: "pu", type: "handakuten"},
		{character: "ペ", romaji: "pe", type: "handakuten"},
		{character: "ポ", romaji: "po", type: "handakuten"},
	],
	katakana_combinations: [
		{character: "キャ", romaji: "kya", type: "yoon"},
		{character: "キュ", romaji: "kyu", type: "yoon"},
		{character: "キョ", romaji: "kyo", type: "yoon"},
		{character: "ギャ", romaji: "gya", type: "yoon_dakuten"},
		{character: "ギュ", romaji: "gyu", type: "yoon_dakuten"},
		{character: "ギョ", romaji: "gyo", type: "yoon_dakuten"},
		{character: "シャ", romaji: "sha", type: "yoon"},
		{character: "シュ", romaji: "shu", type: "yoon"},
		{character: "ショ", romaji: "sho", type: "yoon"},
		{character: "ジャ", romaji: "ja", type: "yoon_dakuten"},
		{character: "ジュ", romaji: "ju", type: "yoon_dakuten"},
		{character: "ジョ", romaji: "jo", type: "yoon_dakuten"},
		{character: "チャ", romaji: "cha", type: "yoon"},
		{character: "チュ", romaji: "chu", type: "yoon"},
		{character: "チョ", romaji: "cho", type: "yoon"},
		{character: "ニャ", romaji: "nya", type: "yoon"},
		{character: "ニュ", romaji: "nyu", type: "yoon"},
		{character: "ニョ", romaji: "nyo", type: "yoon"},
		{character: "ヒャ", romaji: "hya", type: "yoon"},
		{character: "ヒュ", romaji: "hyu", type: "yoon"},
		{character: "ヒョ", romaji: "hyo", type: "yoon"},
		{character: "ビャ", romaji: "bya", type: "yoon_dakuten"},
		{character: "ビュ", romaji: "byu", type: "yoon_dakuten"},
		{character: "ビョ", romaji: "byo", type: "yoon_dakuten"},
		{character: "ピャ", romaji: "pya", type: "yoon_handakuten"},
		{character: "ピュ", romaji: "pyu", type: "yoon_handakuten"},
		{character: "ピョ", romaji: "pyo", type: "yoon_handakuten"},
		{character: "ミャ", romaji: "mya", type: "yoon"},
		{character: "ミュ", romaji: "myu", type: "yoon"},
		{character: "ミョ", romaji: "myo", type: "yoon"},
		{character: "リャ", romaji: "rya", type: "yoon"},
		{character: "リュ", romaji: "ryu", type: "yoon"},
		{character: "リョ", romaji: "ryo", type: "yoon"},
	],
};

/**
 * A collection of common Japanese Kanji characters, organized by category.
 * Each entry includes the kanji character, its romaji reading(s), and its
 * corresponding hiragana reading(s).
 */
export const kanjiCharacters = {
	// Characters related to time (days, months, years, etc.)
	time: [
		{
			character: "日",
			romanji: ["nichi", "jitsu", "hi"],
			hiragana: ["にち", "じつ", "ひ"],
		},
		{
			character: "月",
			romanji: ["getsu", "gatsu", "tsuki"],
			hiragana: ["げつ", "がつ", "つき"],
		},
		{character: "年", romanji: ["nen", "toshi"], hiragana: ["ねん", "とし"]},
		{character: "時", romanji: ["ji", "toki"], hiragana: ["じ", "とき"]},
		{
			character: "分",
			romanji: ["fun", "pun", "bun", "wakeru"],
			hiragana: ["ふん", "ぷん", "ぶん", "わける"],
		},
		{character: "週", romanji: "shū", hiragana: "しゅう"},
		{
			character: "今日", // This is a jukugo (compound word)
			romanji: "kyō",
			hiragana: "きょう",
		},
		{
			character: "明日", // This is a jukugo (compound word)
			romanji: ["ashita", "asu"],
			hiragana: ["あした", "あす"],
		},
	],

	// Common objects
	common_objects: [
		{character: "本", romanji: ["hon", "moto"], hiragana: ["ほん", "もと"]},
		{character: "机", romanji: "tsukue", hiragana: "つくえ"},
		{character: "椅子", romanji: "isu", hiragana: "いす"},
		{character: "戸", romanji: ["to", "ko"], hiragana: ["と", "こ"]},
		{character: "窓", romanji: "mado", hiragana: "まど"},
		{character: "車", romanji: ["kuruma", "sha"], hiragana: ["くるま", "しゃ"]},
		{
			character: "家",
			romanji: ["ie", "uchi", "ka"],
			hiragana: ["いえ", "うち", "か"],
		},
	],

	// Other common, essential words
	other_common_words: [
		{
			character: "人",
			romanji: ["hito", "jin", "nin"],
			hiragana: ["ひと", "じん", "にん"],
		},
		{character: "円", romanji: "en", hiragana: "えん"},
		{character: "水", romanji: ["mizu", "sui"], hiragana: ["みず", "すい"]},
		{character: "火", romanji: ["hi", "ka"], hiragana: ["ひ", "か"]},
		{character: "学校", romanji: "gakkō", hiragana: "がっこう"},
		{
			character: "食べる", // This includes the okurigana (suffix) for verbs
			romanji: "taberu",
			hiragana: "たべる",
		},
		{character: "見る", romanji: "miru", hiragana: "みる"},
		{character: "大きい", romanji: "ōkii", hiragana: "おおきい"},
		{character: "小さい", romanji: "chiisai", hiragana: "ちいさい"},
		{character: "話", romanji: ["hanashi", "wa"], hiragana: ["はなし", "わ"]},
	],
};
